### ISSUE TITLE
[multimap] [map] how to make hazelcast multimap support eviction policy?

### ISSUE THREAD

**Issue by fattyhan** [hazelcast/hazelcast#10920]
As title said,i want to make multimap support eviction policy but all i did was useless,please help me. I had try add imap listener to listening entry expired,i can got it,but it's unable to annotation hazelcast instance on listener class. And i'd try created a inner-class as listener but i can't register it on spring-hazelcast.xml.
If you have some idea please tell me!

**Comment by mmedenjak** [comment]
Related : https://github.com/hazelcast/hazelcast/issues/4601

**Comment by fattyhan** [comment]
Resolved

**Comment by mmedenjak** [comment]
I will close the issue then. Please reopen if you encounter more problems.

**Comment by pnapoliJC** [comment]
@fattyhan How did you resolve this? I'm encountered the same problem, ReplicatedMap does not support eviction, how can I avoid OOM?
@mmedenjak

**Comment by mmedenjak** [comment]
Hi @pnapoliJC !

Replicated map still doesn't support eviction. It's best if you adapt your use case to use IMap and use eviction there. You can probably emulate a replicated map using IMap, depending on your use case.

**Comment by pnapoliJC** [comment]
Thanks for your answer @mmedenjak ,
how can I emulate replicated map with IMap? I need full data replication in every node to notice the performance increase, I'm trying to use it as a cache layer between app and database.
Anyway, does the Hazelcast node have safeguards to prevent OOM crash? Maybe I can simply set a TTL per key.

**Comment by mmedenjak** [comment]
You can set the backup count for the map up to 6. So if you have 7 or less nodes, each member can contain the entire map. Now all you have to do is enable reading from backups and basically you've achieved something like a replicated map.

We don't have safeguards to prevent an out-of-memory since measuring the exact memory footprint is a costly process. You can use TTL and evictions to prevent OOME from happening but it needs to be configured properly according to your use case.

**Comment by fattyhan** [comment]
@pnapoliJC My solution, which is not a formal one, may be a bit of a bug. I register the listener after obtaining the imap, and then do the access operation.
