### ISSUE TITLE
Hazelcast User Code deployment: Loading Custom Bean Jar from Classpath Issue

### ISSUE THREAD

**Issue by bhagathk** [hazelcast/hazelcast#11530]
I am trying to implement the user code deployment feature provided as part of the Hazelcast 3.9-EA.
I am trying to load the Jar with Custom Jar from Classpath using Programmatic Configuration through the hazelcast Client. Hazelcast Documentation says, 
We can load the Custom jar from classpath using " <jarPath>sample.jar</jarPath> " while using the XML configuration.

Below is the Hazelcast Documentation link I referred to implement user code deployment
 
[http://docs.hazelcast.org/docs/latest-development/manual/html/Setting_Up_Clusters/Client_User_Code_Deployment_-_BETA.html](url)

I am using the programmatic configuration, Below is the code I am using to Implement the user code deployment

```java
ClientUserCodeDeploymentConfig clientUserCodeDeploymentConfig = new ClientUserCodeDeploymentConfig();
                        clientUserCodeDeploymentConfig.addJar("TESTBEAN-0.0.1-SNAPSHOT.jar");
                           clientUserCodeDeploymentConfig.setEnabled(true);
```

I am getting the below exception, while loading the Custom Jar from classpath using the above code.

```java
Exception in thread "main" com.hazelcast.core.HazelcastException: java.io.FileNotFoundException: File could not be found in TESTBEAN-0.0.1-SNAPSHOT.jar  and resources/TESTBEAN-0.0.1-SNAPSHOT.jar
              at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:94)
              at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:56)
              at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:52)
              at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:105)
              at com.hazelcast.client.impl.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:417)
              at com.hazelcast.client.HazelcastClientManager.newHazelcastClient(HazelcastClientManager.java:78)
              at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:72)
              at com.walmart.imdg.client1.IMDGClient1.main(IMDGClient1.java:26)
Caused by: java.io.FileNotFoundException: File could not be found in TESTBEAN-0.0.1-SNAPSHOT.jar  and resources/TESTBEAN-0.0.1-SNAPSHOT.jar
              at com.hazelcast.client.spi.impl.ClientUserCodeDeploymentService.getJarInputStream(ClientUserCodeDeploymentService.java:138)
              at com.hazelcast.client.spi.impl.ClientUserCodeDeploymentService.loadClassesFromJar(ClientUserCodeDeploymentService.java:102)
              at com.hazelcast.client.spi.impl.ClientUserCodeDeploymentService.loadClassesFromJars(ClientUserCodeDeploymentService.java:92)
              at com.hazelcast.client.spi.impl.ClientUserCodeDeploymentService.start(ClientUserCodeDeploymentService.java:65)
              at com.hazelcast.client.impl.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:414)
              ... 3 more
```

**Additional Information:** I am creating a Web Based Application. Below the structure in which the Bean Jar will be in the artifact created
 
Client.War
              -WEB-INF/classes
              -WEB-INF/lib
                           -TEST-BEAN-0.0.1-SNAPSHOT

Is this the right way to add the Custom Jar to the User Code Deployment? If not, please suggest me the right approach.

**Comment by mmedenjak** [comment]
Hi @bhagathk !

Looks like the `TESTBEAN-0.0.1-SNAPSHOT.jar` is not found on the classpath of your client WAR. I think this will be corrected by fixing either the location of the jar in the WAR file or correcting the  JAR path that you supply to the Hazelcast API.
Can you move the jar into the `WEB-INF/lib` or and retry?

**Comment by bhagathk** [comment]
Thanks for the Response. When we create the War, The `TESTBEAN-0.0.1-SNAPSHOT.jar` will be placed in the WEB-INF/lib. I even unzipped the War and checked after the artifact is created and I have found the TESTBEAN-0.0.1-SNAPSHOT.jar in the WEB-INF/lib folder.

 How would you suggest I should give the path to the jar to load it from classpath to Hazelcast API?

**Comment by vbekiaris** [comment]
@bhagathk are hazelcast JARs deployed on the app server's classpath or in the web application's classpath? If it's the latter, can you try again, this time providing the current thread's context `ClassLoader` as the client config's classloader? So your client config should look something like this:

```
ClientConfig clientConfig = new ClientConfig();
clientConfig.setClassLoader(Thread.currentThread().getContextClassLoader());
clientConfig.setUserCodeDeploymentConfig(yourUserCodeDeploymentConfig);
...
HazelcastInstance client = HazelcastClient.newHazelcastClient(clientConfig);
```

**Comment by bhagathk** [comment]
I am trying to load the Jars from the Web application's Classpath WEB-INF/lib. I tried in the way you suggested but still getting the same exception. Below is the code I used.

`		ClientConfig clientConfig = new ClientConfig();
		clientConfig.setClassLoader(Thread.currentThread().getContextClassLoader());
		ClientNetworkConfig networkConfig = clientConfig.getNetworkConfig();
		networkConfig.addAddress("ipaddress");
		ClientUserCodeDeploymentConfig clientUserCodeDeploymentConfig = new ClientUserCodeDeploymentConfig();
		clientUserCodeDeploymentConfig.addJar("TESTBEAN-0.0.2-SNAPSHOT.jar");
		clientUserCodeDeploymentConfig.setEnabled(true);`

**Comment by mmedenjak** [comment]
@bhagathk 
One question first - your code tries loading "TESTBEAN-0.0.2-SNAPSHOT.jar" while all of the comments above mentioned "TESTBEAN-0.0.1-SNAPSHOT.jar". Is this an error?
Currently I am unable to try making a WAR myself but can you please use the method below and try out different combinations of `path`:

```java
public String find(ClassLoader classLoader, String path) {
        final File file = new File(path);
        if (file.exists()) {
            return "Found from file";
        }
        try {
            final URL url = new URL(path);
            return "Found as URL";
        } catch (MalformedURLException e) {
        }
        final InputStream resource = classLoader.getResourceAsStream(path);
        if (resource != null) {
            return "Found as resource";
        }
        return null;
    }
```
This method should use the same mechanism as the hazelcast code. You can try different classloaders and quickly try out different paths:

```java
        final ClassLoader classloader1 = Thread.currentThread().getContextClassLoader();
        final ClassLoader classloader2 = ClassLoader.getSystemClassLoader();

        System.out.println(find(classloader1, "TESTBEAN-0.0.2-SNAPSHOT.jar"));
        System.out.println(find(classloader2, "TESTBEAN-0.0.2-SNAPSHOT.jar"));
        
        System.out.println(find(classloader1, "/TESTBEAN-0.0.2-SNAPSHOT.jar"));
        System.out.println(find(classloader2, "/TESTBEAN-0.0.2-SNAPSHOT.jar"));

        System.out.println(find(classloader1, "/WEB-INF/TESTBEAN-0.0.2-SNAPSHOT.jar"));
        System.out.println(find(classloader2, "/WEB-INF/TESTBEAN-0.0.2-SNAPSHOT.jar"));
```

**Comment by bhagathk** [comment]
I just Updated the Bean Jar, That's why there is a change in version. That's not an error.

**Comment by kwart** [comment]
@bhagathk For the proper work of `addJar("module.jar")` you need 2 changes:
* put the `TESTBEAN-0.0.2-SNAPSHOT.jar` on the classpath. I.e.
  * either `WEB-INF/classes` in your web application
    * you will probably want to to place the JAR into `WEB-INF/lib` too, but the `lib` directory is not a classpath root, so this path won't work for `addJar` method
  * or a shared server location for libraries (depends on your web server)
* as @vbekiaris already mentioned configure the correct class loader to locate the JAR within the WAR
  ```java
  ClientConfig clientConfig = new ClientConfig();
  ClientUserCodeDeploymentConfig clientUserCodeDeploymentConfig = new ClientUserCodeDeploymentConfig();
  clientUserCodeDeploymentConfig.addJar("TESTBEAN-0.0.2-SNAPSHOT.jar");
  clientUserCodeDeploymentConfig.setEnabled(true);
  clientConfig.setClassLoader(Thread.currentThread().getContextClassLoader());
  clientConfig.setUserCodeDeploymentConfig(clientUserCodeDeploymentConfig);
  ```
  or
  ```java
  clientConfig.setClassLoader(YourServlet.class.getClassLoader());
  ```

**Comment by bhagathk** [comment]
I am able to get the User code deployment bean's absolute path in the server it is deployed using the following code:
`URL[] classPathEntries=((URLClassLoader) (Thread.currentThread().getContextClassLoader())).getURLs();

					for (URL classPathEntry : classPathEntries) 
					{
					    if(classPathEntry.getPath().contains(USER_CODE_DEPLOYMENT_BEAN))
					    {
					    	UserCodeDeploymentBeanPath = classPathEntry.getFile();
					    	break;
					    }
					}`

@kwart  I will see If can Actually copy the Jar's from WEB-INF/lib to WEB-INF/classes and then setting the classpath as suggested 
`clientConfig.setClassLoader(Thread.currentThread().getContextClassLoader());`

**Comment by mmedenjak** [comment]
@bhagathk were you able to copy the JAR and set the classpath as suggested?

**Comment by bhagathk** [comment]
Yes I am able to successfully do the user code deployment.

**Comment by bhagathk** [comment]
Yes I am able to successfully do the user code deployment.
